export {default as Header} from './Header/Header';
export {default as Main} from './Main/Main';
export {default as Service} from './Service/Service';
export {default as Menu} from './Menu/Menu';
export {default as About} from './About/About';
export {default as Reviews} from './Reviews/Reviews';
export {default as Contact} from './Contact/Contact';
export {default as Blogs} from './Blogs/Blogs';
export {default as Footer} from './Footer/Footer';